
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BRACE_CLOSE BRACE_OPEN CIDR4 COMMA DOMAIN FLOAT INTEGER IPADDR MACADDR NAME SEMICOLON STRINGcontent :content : content entry\n    value : IPADDR\n          | DOMAIN\n          | MACADDR\n          | STRING\n          | INTEGER\n          | FLOAT\n          | NAME\n          | CIDR4\n    value_list : value COMMA valuevalue_list : value_list COMMA value\n    key_part : NAME\n             | DOMAIN\n             | IPADDR\n             | MACADDR\n             | STRING\n             | INTEGER\n             | FLOAT\n             | CIDR4\n    key : key_partkey : key key_part\n    entry : key value SEMICOLON\n          | key value_list SEMICOLON\n          | key block\n          | key block SEMICOLON\n    \n    entry : value SEMICOLON\n    block : BRACE_OPEN content BRACE_CLOSE'
    
_lr_action_items = {'BRACE_OPEN':([2,3,4,6,7,8,9,10,11,12,16,],[-20,-19,14,-14,-13,-21,-16,-15,-17,-18,-22,]),'CIDR4':([0,1,2,3,4,5,6,7,8,9,10,11,12,14,16,17,19,20,21,22,23,24,25,26,],[-1,2,-20,-19,2,-2,-14,-13,-21,-16,-15,-17,-18,-1,-22,-25,-27,2,34,-24,-26,34,-23,-28,]),'FLOAT':([0,1,2,3,4,5,6,7,8,9,10,11,12,14,16,17,19,20,21,22,23,24,25,26,],[-1,3,-20,-19,3,-2,-14,-13,-21,-16,-15,-17,-18,-1,-22,-25,-27,3,29,-24,-26,29,-23,-28,]),'DOMAIN':([0,1,2,3,4,5,6,7,8,9,10,11,12,14,16,17,19,20,21,22,23,24,25,26,],[-1,6,-20,-19,6,-2,-14,-13,-21,-16,-15,-17,-18,-1,-22,-25,-27,6,32,-24,-26,32,-23,-28,]),'STRING':([0,1,2,3,4,5,6,7,8,9,10,11,12,14,16,17,19,20,21,22,23,24,25,26,],[-1,11,-20,-19,11,-2,-14,-13,-21,-16,-15,-17,-18,-1,-22,-25,-27,11,31,-24,-26,31,-23,-28,]),'BRACE_CLOSE':([5,14,17,19,20,22,23,25,26,],[-2,-1,-25,-27,26,-24,-26,-23,-28,]),'SEMICOLON':([2,3,6,7,9,10,11,12,13,15,17,18,26,27,28,29,30,31,32,33,34,35,36,],[-10,-8,-4,-9,-5,-3,-6,-7,19,22,23,25,-28,-9,-5,-8,-3,-6,-4,-7,-10,-12,-11,]),'NAME':([0,1,2,3,4,5,6,7,8,9,10,11,12,14,16,17,19,20,21,22,23,24,25,26,],[-1,7,-20,-19,7,-2,-14,-13,-21,-16,-15,-17,-18,-1,-22,-25,-27,7,27,-24,-26,27,-23,-28,]),'MACADDR':([0,1,2,3,4,5,6,7,8,9,10,11,12,14,16,17,19,20,21,22,23,24,25,26,],[-1,9,-20,-19,9,-2,-14,-13,-21,-16,-15,-17,-18,-1,-22,-25,-27,9,28,-24,-26,28,-23,-28,]),'IPADDR':([0,1,2,3,4,5,6,7,8,9,10,11,12,14,16,17,19,20,21,22,23,24,25,26,],[-1,10,-20,-19,10,-2,-14,-13,-21,-16,-15,-17,-18,-1,-22,-25,-27,10,30,-24,-26,30,-23,-28,]),'COMMA':([2,3,6,7,9,10,11,12,15,18,27,28,29,30,31,32,33,34,35,36,],[-10,-8,-4,-9,-5,-3,-6,-7,21,24,-9,-5,-8,-3,-6,-4,-7,-10,-12,-11,]),'INTEGER':([0,1,2,3,4,5,6,7,8,9,10,11,12,14,16,17,19,20,21,22,23,24,25,26,],[-1,12,-20,-19,12,-2,-14,-13,-21,-16,-15,-17,-18,-1,-22,-25,-27,12,33,-24,-26,33,-23,-28,]),'$end':([0,1,5,17,19,22,23,25,26,],[-1,0,-2,-25,-27,-24,-26,-23,-28,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'key_part':([1,4,20,],[8,16,8,]),'block':([4,],[17,]),'key':([1,20,],[4,4,]),'entry':([1,20,],[5,5,]),'value_list':([4,],[15,]),'content':([0,14,],[1,20,]),'value':([1,4,20,21,24,],[13,18,13,35,36,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> content","S'",1,None,None,None),
  ('content -> <empty>','content',0,'p_content_empty','confuseparse.py',74),
  ('content -> content entry','content',2,'p_content','confuseparse.py',79),
  ('value -> IPADDR','value',1,'p_value','confuseparse.py',86),
  ('value -> DOMAIN','value',1,'p_value','confuseparse.py',87),
  ('value -> MACADDR','value',1,'p_value','confuseparse.py',88),
  ('value -> STRING','value',1,'p_value','confuseparse.py',89),
  ('value -> INTEGER','value',1,'p_value','confuseparse.py',90),
  ('value -> FLOAT','value',1,'p_value','confuseparse.py',91),
  ('value -> NAME','value',1,'p_value','confuseparse.py',92),
  ('value -> CIDR4','value',1,'p_value','confuseparse.py',93),
  ('value_list -> value COMMA value','value_list',3,'p_value_list_start','confuseparse.py',99),
  ('value_list -> value_list COMMA value','value_list',3,'p_value_list','confuseparse.py',104),
  ('key_part -> NAME','key_part',1,'p_key_part','confuseparse.py',110),
  ('key_part -> DOMAIN','key_part',1,'p_key_part','confuseparse.py',111),
  ('key_part -> IPADDR','key_part',1,'p_key_part','confuseparse.py',112),
  ('key_part -> MACADDR','key_part',1,'p_key_part','confuseparse.py',113),
  ('key_part -> STRING','key_part',1,'p_key_part','confuseparse.py',114),
  ('key_part -> INTEGER','key_part',1,'p_key_part','confuseparse.py',115),
  ('key_part -> FLOAT','key_part',1,'p_key_part','confuseparse.py',116),
  ('key_part -> CIDR4','key_part',1,'p_key_part','confuseparse.py',117),
  ('key -> key_part','key',1,'p_key_single','confuseparse.py',123),
  ('key -> key key_part','key',2,'p_key','confuseparse.py',128),
  ('entry -> key value SEMICOLON','entry',3,'p_entry','confuseparse.py',138),
  ('entry -> key value_list SEMICOLON','entry',3,'p_entry','confuseparse.py',139),
  ('entry -> key block','entry',2,'p_entry','confuseparse.py',140),
  ('entry -> key block SEMICOLON','entry',3,'p_entry','confuseparse.py',141),
  ('entry -> value SEMICOLON','entry',2,'p_entry_nokey','confuseparse.py',148),
  ('block -> BRACE_OPEN content BRACE_CLOSE','block',3,'p_block','confuseparse.py',154),
]
